/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionConfirmationModal: typeof import('./src/components/ActionConfirmationModal.vue')['default']
    ActionControlPanel: typeof import('./src/components/ActionControlPanel.vue')['default']
    AddingForm: typeof import('./src/components/AddingForm.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    BaseIcons: typeof import('./src/components/BaseIcons.vue')['default']
    BasePanelIcon: typeof import('./src/components/BasePanelIcon.vue')['default']
    BaseUsage: typeof import('./src/components/BaseUsage.vue')['default']
    ConfirmationForm: typeof import('./src/components/ConfirmationForm.vue')['default']
    EditingForm: typeof import('./src/components/EditingForm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    FormSubtasks: typeof import('./src/components/FormSubtasks.vue')['default']
    NavbarTodo: typeof import('./src/components/NavbarTodo.vue')['default']
    Not: typeof import('./src/components/Not.vue')['default']
    NoteCardTodo: typeof import('./src/components/NoteCardTodo.vue')['default']
    NoteCascader: typeof import('./src/components/NoteCascader.vue')['default']
    NoteInput: typeof import('./src/components/NoteInput.vue')['default']
    'NotesСalendar': typeof import('./src/components/NotesСalendar.vue')['default']
    NotesForm: typeof import('./src/components/NotesForm.vue')['default']
    NotesInput: typeof import('./src/components/NotesInput.vue')['default']
    NoteSubtasksItem: typeof import('./src/components/NoteSubtasksItem.vue')['default']
    OpenDescBaseButton: typeof import('./src/components/OpenDescBaseButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarToSide: typeof import('./src/components/SidebarToSide.vue')['default']
    SideberAside: typeof import('./src/components/SideberAside.vue')['default']
    TaskCompletionTracking: typeof import('./src/components/TaskCompletionTracking.vue')['default']
    TheListTodo: typeof import('./src/components/TheListTodo.vue')['default']
    'TheModalСonfirmation': typeof import('./src/components/TheModalСonfirmation.vue')['default']
    TheSidebarRouters: typeof import('./src/components/TheSidebarRouters.vue')['default']
    TheTodoList: typeof import('./src/components/TheTodoList.vue')['default']
    TodoCard: typeof import('./src/components/TodoCard.vue')['default']
    TodoCardDescription: typeof import('./src/components/TodoCardDescription.vue')['default']
    UpdataBaseButton: typeof import('./src/components/UpdataBaseButton.vue')['default']
  }
}
